### ISSUE TITLE
Still timing out after 5 minutes

### ISSUE THREAD

**Issue by stephanebruckert** [Ullaakut/nmap#102]
It's likely I'm missing something obvious but when I run nmap on a large port range (ANY/ANY), I get this after 5 minutes:

> 2022/09/06 15:10:34 unable to run nmap scan: nmap scan timed out

Although I've set all Timeouts possible:

	scanner, err := nmap.NewScanner(
		nmap.WithTargets(hostname.AllowedIPRanges...),
		nmap.WithScripts("ssl-cert"),
		nmap.WithContext(ctx),
		nmap.WithVerbosity(3),
		nmap.WithScriptTimeout(60*time.Minute),
		nmap.WithHostTimeout(60*time.Minute),
		nmap.WithInitialRTTTimeout(60*time.Minute),
		nmap.WithMaxRTTTimeout(60*time.Minute),
	)

Any idea? Thanks!

**Comment by zekiahmetbayar** [comment]
Hi @stephanebruckert!,

I think it happens because of the ctx background parameter.

Can you try removing the parameter or replacing it with the following?

```
ctx := context.Background()
scanner, err := nmap.NewScanner(
	...
	nmap.WithContext(ctx),
	...
)
```

**Comment by stephanebruckert** [comment]
That was it... 😄 thank you!
