### ISSUE TITLE
Run the nmap scanned with custom arguments

### ISSUE THREAD

**Issue by varsraja** [Ullaakut/nmap#112]
Hi,
can you provide an example for running the nmap scanned with custom arguments. 
When i try to run the following
default:[-O -sS -p 22,53,80,110,143,8080,3011,4564 -R] 
as follows
scanner, err := nmap.NewScanner(
		nmap.WithCustomArguments(strings.Join(args, " ")),
		nmap.WithTargets(nw.Subnet),
		nmap.WithInterface(intfName),
		nmap.WithContext(ctx),
	)

The actual scan
shows 
 Running nmap scan on 192.170.0.1/24 with [ 192.170.0.1/24 -e ]

**Comment by varsraja** [comment]
@elivlo  
My bad,  i was mislead by the warning displayed in vscode for my code
It works fine when  i give  like this 

We have different profiles to run 
So we  load a map like this 
type Profile struct {
	Name string   `json:"name"`
	Args []string `json:"args"`
}
where against each name , we have the args 
{
    "profiles": [
      {
        "args": ["-O", "-sS", "-p", "22,53,80,110,143,443,8080,3011,4564", "-R"],
        "name": "default"
      }
    ]
}

	scanner, err := nmap.NewScanner(
		nmap.WithCustomArguments(args),
		nmap.WithTargets(nw.Subnet),
		nmap.WithInterface(intfName),
		nmap.WithContext(ctx),
	)

**Comment by Ullaakut** [comment]
Thanks @varsraja ! Have a nice day then :) Feel free to reopen if something is unclear.
