### ISSUE TITLE
Memory Usage is too high when using Progress(...)

### ISSUE THREAD

**Issue by gnuletik** [Ullaakut/nmap#117]
When running nmap with service info and progression, the memory usage is above 1GB in around 10 minutes. Which seems quite high.

```go
	scanner, err := nmap.NewScanner(
		ctx,
		nmap.WithTargets(target),
		nmap.WithPorts("0-6000"),
		nmap.WithServiceInfo(),
	)
	if err != nil {
		return fmt.Errorf("nmap.NewScanner: %w", err)
	}

	progress := make(chan float32)

	result, warnings, err := scanner.Progress(progress).Run()
```

I see multiple way to reduce the memory usage:
- Using the `ToFile` function to store the nmap XML result to a file, as suggested in https://github.com/Ullaakut/nmap/pull/69. However, this makes the Progress value to always be 0.
- Makes the progress report duration configurable. It is currently hard-coded to 100ms: https://github.com/Ullaakut/nmap/blob/a7503243d25b206a78311f83a66ecd55bb5e36fe/nmap.go#L77 https://github.com/Ullaakut/nmap/blob/a7503243d25b206a78311f83a66ecd55bb5e36fe/nmap.go#L173 But I guess that this solution would not properly fix the issue.
- Avoid storing all the TaskProgress values and only keep the last one.

Do you see other possible fixes?

Thanks!

**Comment by Ullaakut** [comment]
I don't think the gigabyte of used RAM is due to the task progress slice, or to the output kept in memory. The nmap outputs amounts to maybe a few megabytes on a very large scan, and 10 minutes of progress reports every 100ms would mean 6000 structs that are each a few bytes, so likely only takes a few kilobytes.

The ram usage most likely comes from the dependencies of this library and Go's policy for garbage collection. 1GB usage doesn't necessarily mean that the program is using 1GB right now, it only means that it reserved 1GB (probably because the total allocations amount to 1GB) but if the system tries to get some of that memory back, the garbage collector will free what's not in use.

I could do a proper benchmark if this becomes a real issue, but so far from my testing the consumption seems to be nothing out of the ordinary.

**Comment by gnuletik** [comment]
Thanks for the feedback!

When removing the `scanner.Progress(...)` configuration, the memory usage is kept below a 100MB after 10 minutes, so that's why I thought that this is linked to the task progress slice.

About the Go's policy for garbage collection: the issue occurred in a container / Kubernetes environment with a memory request and limit set to 1GB. During multiple runs, the container was OOMKilled, which means that the real memory used was above 1GB.

I'll try to use the `GOMEMLIMIT` env variable to set configure the GC.

**Comment by Ullaakut** [comment]
Ah, that is interesting 🤔 There is then indeed an issue with the progress mode. We need to look into it! Will update the labels accordingly.

**Comment by Ullaakut** [comment]
TODO, in case someone else picks it up:

* Run memory usage benchmarks with and without Progress enabled
* Compare benchmarks to find source of memory hunger
* Fix it

**Comment by gnuletik** [comment]
I made more tests with `nmap.NewScanner(ctx, nmap.WithPorts("-"), nmap.WithServiceInfo())`

I run a first scan without `nmap.Progress(...)`.

Here is the memory usage:

<img width="671" alt="Screenshot 2023-07-17 at 16 58 42" src="https://github.com/Ullaakut/nmap/assets/9059840/ae6f0f26-be9b-4e74-89d5-41d10d7ea465">

Then I run another container with:
- `nmap.Progress(...)`.
- Memory request & limit on the kubernetes pod: `2Gi`
- Environment variable `GOMEMLIMIT=1932735283` (90% of the memory request/limit)

Here is the memory usage:

<img width="667" alt="Screenshot 2023-07-17 at 17 01 07" src="https://github.com/Ullaakut/nmap/assets/9059840/d6fd6775-7295-4f3f-9a89-e3d73859a749">

The container ended with a OOMKilled error from Kubernetes.

**Comment by Ullaakut** [comment]
This looks like a serious issue indeed. Thanks for the details! I'll try to find some time to fix this, alongside the build and fixing the CI.

**Comment by llwq123456** [comment]
@Ullaakut hello, Are SIGUSR1 and SIGUSR2 signals used in this project？

**Comment by Ullaakut** [comment]
@llwq123456 No

**Comment by gnuletik** [comment]
https://github.com/Ullaakut/nmap/releases/tag/v3.0.4 seems to have fixed the issue!


<img width="1342" alt="Screenshot 2024-10-15 at 00 24 30" src="https://github.com/user-attachments/assets/9e5f23d1-9bc7-48fe-a158-0baaf783702e">
<img width="1341" alt="Screenshot 2024-10-15 at 00 24 54" src="https://github.com/user-attachments/assets/e7a44559-793c-4e29-b891-53d117836f19">

Thanks 🔥
