### ISSUE TITLE
The basic_scan_async demo cannot output the results in real time on the console

### ISSUE THREAD

**Issue by zan8in** [Ullaakut/nmap#119]
The basic_scan_async demo cannot output the results in real time on the console

**Comment by Ullaakut** [comment]
It works fine for me:

```bash
go run examples/basic_scan_async/main.go
Host "172.217.20.206":
        Port 80/tcp open http
        Port 443/tcp open https
        Port 843/tcp filtered unknown
Host "163.70.128.35":
        Port 80/tcp open http
        Port 443/tcp open https
        Port 843/tcp closed unknown
Host "142.250.179.110":
        Port 80/tcp open http
        Port 443/tcp open https
        Port 843/tcp filtered unknown
```

What is the error you got when you tried running it? Could you give some more information?

**Comment by zan8in** [comment]
Is it possible to display the scanning results of each port in real-time on the console, rather than waiting for the entire scan to complete before showing the complete results, similar to the functionality of masscan? For example, when executing a command like "nmap -p - 192.168.1.1/24 -Pn," I would like each port to be displayed on the console as soon as it is scanned, without having to wait for the scan to finish.

**Comment by Ullaakut** [comment]
No, not with nmap.
