### ISSUE TITLE
unable to create nmap scanner: nmap binary was not found

### ISSUE THREAD

**Issue by hurricane1988** [Ullaakut/nmap#120]
I use Mac M1 as development environment, “unable to create nmap scanner: nmap binary was not found” when I run the sample.

**Comment by civilizeddev** [comment]
This library requires **nmap** to be installed on your computer to work.

https://github.com/Ullaakut/nmap/blob/a7503243d25b206a78311f83a66ecd55bb5e36fe/nmap.go#L59-L62

I too was someone who mistakenly thought this library had built-in **nmap** functionality.

**Comment by Ullaakut** [comment]
Thank you @civilizeddev , closing this topic :)
