### ISSUE TITLE
How we can do the OS scan with root privileges

### ISSUE THREAD

**Issue by balaji-dongare** [Ullaakut/nmap#121]
my Application is running on docker container while scanning os got error:[TCP/IP fingerprinting (for OS scan) requires root privileges. QUITTING! EOF]

**Comment by awei84** [comment]
Hello, I'd like to know how you finally dealt with this problem.

**Comment by Ullaakut** [comment]
Hi @awei84 ! Can you describe your problem? I will try to help you.
