### ISSUE TITLE
nmap.WithOSDetection()

### ISSUE THREAD

**Issue by qt-wu** [Ullaakut/nmap#123]
Probe one IP, why do multiple host.OS.Matches return

```go
for _, host := range result.Hosts {
	for _, match := range host.OS.Matches {
		for _, class := range match.Classes {
			switch class.OSFamily() {
			case osfamily.Linux:
				linux++
			case osfamily.Windows:
				windows++
			}
		}
	}
}
```

**Comment by Ullaakut** [comment]
Hi @qt-wu !

This is default nmap behavior:

> When Nmap is unable to detect a perfect OS match, it sometimes offers up near-matches as possibilities.

See [this stackoverflow post](https://security.stackexchange.com/questions/121964/nmap-shows-multiple-outputs-in-os-detection) for more information.
