### ISSUE TITLE
Goroutine never finishes if process is killed

### ISSUE THREAD

**Issue by botastic** [Ullaakut/nmap#17]
Hey there,

I stumbled upon a probable memory leak in the `Run` function. If the Command is killed, because the timeout is reached, the goroutine waiting for cmd.Wait() to return will never finish.
This is because the done channel is not buffered and the error is never retrieved in the select statement.

Here's an [example](https://play.golang.org/p/POcAXmdERsC) I put together. I also found this related [stackoverflow post (see comments)](https://stackoverflow.com/a/11886829).

I did not create a PR, because the solution is pretty straight forward - Simply make a buffered channel.

```go
	// Make a goroutine to notify the select when the scan is done.
	done := make(chan error, 1)
	go func() {
		done <- cmd.Wait()
	}()
```

Have a nice day

**Comment by Ullaakut** [comment]
Thanks @botastic ! Will fix that :)
