### ISSUE TITLE
Add Progress function to easily stream progress updates from AsyncRun method

### ISSUE THREAD

**Issue by TerminalFi** [Ullaakut/nmap#32]
* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request
  - [ ] support request

* **What is the current behavior?**
AsyncRun returns bufio reader, allowing users to manipulate the data to have it perform in several different manners. However some users might only want to use AsyncRun for being able to stream progress. It would be nice to have a `Progress` function that would allow streaming progress without having a bunch of code to accompany it.

* **What is the expected behavior?**
Call `range Progress(content) {}` and have progress updates printed to screen

* **What is the motivation / use case for changing the behavior?**
Allow an easier to use Progress implementation allowing straight forward implementation of parsing Nmap xml bytes from the stream and getting progress status.

**Comment by elivlo** [comment]
@TerminalFi 
Closing this issue because it should be resolved in version v3.0.0. Please reopen it if needed!
