### ISSUE TITLE
How to scan subnet 192.168.0.0/24

### ISSUE THREAD

**Issue by mydockergit** [Ullaakut/nmap#42]
How can I use this library to scan for all the live hosts on the network 182.168.0.0/24 ?

**Comment by mydockergit** [comment]
Found:
```
	scanner, err := nmap.NewScanner(
		nmap.WithTargets("192.168.0.0/24"),
		nmap.WithFastMode(),
		nmap.WithOSDetection(),
```

**Comment by Ullaakut** [comment]
Yes, sorry about the delay but you're right :) Was the documentation not clear? If there are pain points you found while using this library, feel free to let me know!
