### ISSUE TITLE
Added error type and enhanced the error checking

### ISSUE THREAD

**Issue by noneymous** [Ullaakut/nmap#44]
Hi,

I further improved our error handling by 
- adding a new kind of error I ran into
- checking for certain known errors in stderr (our slice of warnings) before trying to parse the XML output

Previously, our first check was whether we can parse the Nmap XML output. That XML is inevitably broken if Nmap terminated with an error. We always returned 'ErrParseOutput' and the details of the error could be revealed by looking at the warnings. 

![grafik](https://user-images.githubusercontent.com/31357019/75537225-ebcbbe00-5a16-11ea-8af9-258887d8ab1e.png)

In the picutre above, you can see how the returned error is 'ErrParseOutput', although, the primary issue was 'malloc failed'.

Now, we can check for common/known errors before trying to parse the output XML and return with more accurate errors.

Best regards!

**Comment by Ullaakut** [comment]
Fixed by #45
