### ISSUE TITLE
OS detection: no matches returned

### ISSUE THREAD

**Issue by hazcod** [Ullaakut/nmap#47]
Hi, using following Options:
```go
			nmap.WithServiceInfo(),
			nmap.WithContext(ctx),
			nmap.WithTargets(ip.String()),
			nmap.WithPrivileged(),
			nmap.WithTimingTemplate(nmap.TimingAggressive),
			nmap.WithSYNScan(),
			nmap.WithOSDetection(),
			nmap.WithOSScanGuess(),
			nmap.WithMostCommonPorts(NmapCommonTopPorts),
			nmap.WithVersionAll(),
```

However this returns no OS matches for an AWS CloudFront server, while a simple invocation of `nmap -O <ip>` does. Any ideas why?

**Comment by Ullaakut** [comment]
Hi @hazcod! No need to edit out your own question, there's no shame in that, and some other people might get the same problem :) What was the reason for that issue in the end if I may ask?

**Comment by hazcod** [comment]
Hi @Ullaakut , it's more to not confuse others. :-)
I'm scanning from a docker container with root/added capabilities but the OS detection of Amazon Cloudfront servers seems to be a hit & miss.. works fine when I run nmap baremetal.

**Comment by Ullaakut** [comment]
I see, thanks :)
