### ISSUE TITLE
Feature: vuln script output

### ISSUE THREAD

**Issue by hazcod** [Ullaakut/nmap#48]
Hi, would it be possible to use the output of the nmap scripts `vuln` using this library?
I don't see it appearing in the XML output.

**Comment by Ullaakut** [comment]
Hi again @hazcod ! :)

It should be in the report, under `Host.Port.Scripts` I guess, and should look like [this](https://github.com/Ullaakut/nmap/blob/master/xml.go#L246).

If that doesn't work for you, please show me the XML output that you get and I'll take a look :)

**Comment by hazcod** [comment]
Missed that one, thanks @Ullaakut !
