### ISSUE TITLE
how i get mac address?

### ISSUE THREAD

**Issue by gakkiyomi** [Ullaakut/nmap#53]
im a rookie
i just run ur example ,but i cant get mac address
i cant find any func get mac addr like  nmap -RP 
![image](https://user-images.githubusercontent.com/41406557/94391611-809ec180-0188-11eb-9838-78e1831c74a5.png)

**Comment by gakkiyomi** [comment]
i got it

**Comment by wenhsinhsieh** [comment]
Could you please share how do you get the mac address?

**Comment by Ullaakut** [comment]
@wenhsinhsieh see https://nmap.org/book/man-host-discovery.html
