### ISSUE TITLE
add a go.mod file and make a semver-numbered release

### ISSUE THREAD

**Issue by dmitris** [Ullaakut/nmap#54]
Would you consider adding a `go.mod` file (can be created with: `go mod init github.com/Ullaakut/nmap` and after merging, creating a release (even if v0.x.x-numbered like v0.5.0 or similar)?  It would make it easier to use as dependency.  Thanks.

**Comment by dmitris** [comment]
@Ullaakut could you also cut publish a new release or add a new git tag?  Since the module name doesn't have `/v2` at the end, it would be great if it could be a `v0.x` or `v1.x` release (or tag), but not sure if it would pass with the existing releases.  Thanks!

**Comment by Ullaakut** [comment]
Oh, right, forgot that this library was already in v2.0, I'll make another PR to add the v2 to the module, sorry about that.
