### ISSUE TITLE
Broken WithResumePreviousScan function

### ISSUE THREAD

**Issue by elivlo** [Ullaakut/nmap#61]
- **I'm submitting a ...**
  - [x] bug report

___
- **Current behavior:**
When running s scan with `WithResumePreviousScan("testfilename")` function, the nmap scan won't start.
![grafik](https://user-images.githubusercontent.com/28390981/98656846-7227f600-2341-11eb-933a-67ddd9d78a86.png)
![grafik](https://user-images.githubusercontent.com/28390981/98656898-84a22f80-2341-11eb-8847-a90ff7b20b87.png)

- **What is the output from nmap directly?**
![grafik](https://user-images.githubusercontent.com/28390981/98657131-d0ed6f80-2341-11eb-81bb-4a29b9243210.png)

___
- **What needs to be changed to work properly?**

1. **Remove** all arguments except `--resume <filename>`
![grafik](https://user-images.githubusercontent.com/28390981/98657362-127e1a80-2342-11eb-9a3c-cfe1c242ecb6.png)

2.  **Reload** the current file content in front of the resuming nmap xml output...
![grafik](https://user-images.githubusercontent.com/28390981/98658002-d0090d80-2342-11eb-8bbb-8ee1e9eab7eb.png)
... because it will only append new xml and does not starting from beginning.
![grafik](https://user-images.githubusercontent.com/28390981/98659054-07c48500-2344-11eb-9a51-70d260d69639.png)

**Comment by Ullaakut** [comment]
Nice, I never used that feature so I didn't know. We can indeed add a check in the `Run` methods to not add the XML options if the Resume option is set :)

**Comment by elivlo** [comment]
Nice! Thank you @ohDaddyPlease
