### ISSUE TITLE
Problem with proxy.golang.org

### ISSUE THREAD

**Issue by elivlo** [Ullaakut/nmap#67]
Hi, 
I'm sorry for asking this!
But while we resolved that issue #65 we got a new problem with go module versions.

- When you clean your cache with `go clean -modcache`
- ... delete the go path
- ... and then run `go get github.com/Ullaakut/nmap/v2`

=> The official Go Proxy does not recognize the changes.
=> You can try this by calling the function `RunWithProgress` in version v2.0.2.

So I'm asking you to set a new Tag (v2.0.3) so hopefully the changes will be cached by Go.

**Comment by sp3t3rs** [comment]
I can confirm this issue. Reproduction can be done as following:

First, get the latest V2-Version: `go get -v github.com/Ullaakut/nmap/v2`. Then, in your $GOPATH, search for the nmap.go file and grep for that particular missing method: `cat '/home/speters/.gvm/pkgsets/go1.14/global/pkg/mod/github.com/!ullaakut/nmap/v2@v2.0.2/nmap.go' | grep "RunWithProgress"`. **You'll see that this method is not found**.

Then, clean the cache, set $GOPROXY to direct to avoid using proxy.golang.org, and then get the latest V2-Version again: `go clean -modcache -cache &&  export GOPROXY=direct && go get -v github.com/Ullaakut/nmap/v2`. **Now, grepping for that method successfully returns the desired part of the code**:

```
cat '/home/speters/.gvm/pkgsets/go1.14/global/pkg/mod/github.com/!ullaakut/nmap/v2@v2.0.2/nmap.go' | grep "RunWithProgress"
// RunWithProgress runs nmap synchronously and returns the result of the scan.
func (s *Scanner) RunWithProgress(liveProgress chan<- float32) (result *Run, warnings []string, err error) {
```
I'd say @elivlo's solution is the proper one, at least proxy.golang.org also suggests setting a new tag:
https://proxy.golang.org/, Section "I removed a bad release from my repository but it still appears in the mirror, what should I do?"

Cheers
Simon

**Comment by Ullaakut** [comment]
I pushed a v2.0.3 version, let me know if that fixes it :)

**Comment by elivlo** [comment]
Now it is working, contains all current methods and does not throw a checksum mismatch. :smiley: 
Thanks!
