### ISSUE TITLE
Does this support Windows or Mac?

### ISSUE THREAD

**Issue by JustinTimperio** [Ullaakut/nmap#72]
Hi all,

I'm a contributor to [ToRat](https://github.com/lu4p/ToRat) and I'm in the process of using this module [to add service and port detection features](https://github.com/lu4p/ToRat/pull/224) to the ToRat client. So far I have been unable to get this module to work when compiling to Windows. 

Does this package support Windows?

**Comment by Ullaakut** [comment]
Hi @JustinTimperio,

Can you show me how you attempted to use the package? Did you specify the `WithBinaryPath` argument? It is not required for UNIX systems (Linux and MacOS) but for Windows, I'm pretty sure it is mandatory, though I never tried running it on Windows.

**Comment by JustinTimperio** [comment]
Hi @Ullaakut, that was probably the issue. I was cross-compiling with the same arguments expecting it to work natively. 

I was able to get [a prototype working for UNIX systems](https://github.com/JustinTimperio/ToRat/tree/feature-nmap) but sadly we need an embedded version of Nmap (IE: dependency-less)
