### ISSUE TITLE
No output options

### ISSUE THREAD

**Issue by brutalgg** [Ullaakut/nmap#73]
There does not appear to be a way to also create standard nmap output files while using this library. Is that something that could be considered for a feature or was it conscious omission?

**Comment by elivlo** [comment]
Hi, as far as I can tell, it was conscious omission when the module was created because it is intended to only handle xml output for later processing. Am I right? @Ullaakut 

But as an additional feature we could add another option to also write the standard stdout directly to a given file/path.
