### ISSUE TITLE
Get port details

### ISSUE THREAD

**Issue by jiaocoll** [Ullaakut/nmap#79]
How can i get the details like this of open port
![image](https://user-images.githubusercontent.com/62785738/115942482-17441e80-a4dd-11eb-83c5-74622328b54b.png)

**Comment by noneymous** [comment]
This is script output.

1) You'll need to make sure the "fingerprint-strings" script is executed, via the scan arguments
2) Depending on the script type, it will be output assigned to a certain port or the host.

```golang
// Host script
for _, host := range result.Hosts {
	for _, hostScript := range host.HostScripts {

		script := hostScript.ID
		scriptOutput := hostScript.Output
	}
}
```



```golang
// Port script
for _, host := range result.Hosts {
	for _, port := range host.Ports {
		for _, portScript := range port.Scripts {

			script := portScript.ID
			scriptOutput := portScript.Output
		}
	}
}
```

**Comment by jiaocoll** [comment]
Thank you very much:)




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Ullaakut/nmap"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月28日(星期三) 下午5:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Ullaakut/nmap] Get port details (#79)





 
This is script output.
  
You'll need to make sure the "fingerprint-strings" script is executed, via the scan arguments
 
Depending on the script type, it will be output assigned to a certain port or the host.
  // Host script for _, host := range result.Hosts { 	for _, hostScript := range host.HostScripts { 		script := hostScript.ID 		scriptOutput := hostScript.Output 	} }
 // Port script for _, host := range result.Hosts { 	for _, port := range host.Ports { 		for _, portScript := range port.Scripts { 			script := portScript.ID 			scriptOutput := portScript.Output 		} 	} }

**Comment by Ullaakut** [comment]
Hi @jiaocoll and @noneymous !

Thanks for your help @noneymous :) Can we mark the issue as solved?

**Comment by jiaocoll** [comment]
Okay!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Brendan Le ***@***.***&gt;; 
发送时间: 2021年4月28日(星期三) 晚上9:20
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Ullaakut/nmap] Get port details (#79)






***@***.******@***.***!

***@***.***：）我们可以将问题标记为已解决吗？

—
你收到这个是因为你被提到了。
直接回复此邮件，在GitHub上查看，或取消订阅.
