### ISSUE TITLE
Parsing Nmap output misses "osclass" data

### ISSUE THREAD

**Issue by noneymous** [Ullaakut/nmap#8]
Hi there!

First of all: awesome library, thank you very much!

It appears to me that parsing Nmap output does not read the osclass data correctly. I've seen there is a solved issue regarding the same thing ( #https://github.com/Ullaakut/nmap/issues/7). However I still have the problem, even though I'm running on your latest version.

"osmatch" data is read correctly. "osclass" data is always empty. Looking at the original Nmap XML data, "osclass" is a child of each "osmatch". In your xml.go specification, they are on the same level. 

Moving 
`Classes      []OSClass       'xml:"osclass" json:"os_classes"'`
from the "OS" struct to the "OSMatch" struct would solve the issue... if that was an acceptable solution to you

best regards!

**Comment by noneymous** [comment]
Using Nmap 7.7

**Comment by Ullaakut** [comment]
Damn, just saw this today, awfully sorry about that. I'll take a look into it this evening, thanks :)

**Comment by Ullaakut** [comment]
I think the recently merged PRs fixed this :) Let me know if you still have issues!
