### ISSUE TITLE
nmap command line options duplication after several repeated invocations

### ISSUE THREAD

**Issue by sm97** [Ullaakut/nmap#81]
I use nmap library to continuosly scan network so I call Run() method repeatedly for single nmap.Scanner structure.
After several invocations Run() starts returning "nmap scan timed out" error.

Using strace utility I found following command line for nmap:
execve("/usr/bin/nmap", ["/usr/bin/nmap", "192.168.xx.xxx/29", "xxx.xxx.xxx.xx", "-p", "443", "-T4", "--script=xxxxxxxxxxx", "-oX", "-", "-oX", "-", "-oX", "-", "-oX", "-", "-oX", "-", "-oX", "-", "-oX", "-", "-oX", "-", "-oX", "-", "-oX", "-", "-oX", "-", "-oX", "-", "-oX", ...], 0xc0003ce040 /* 6 vars */ <unfinished ...>

I think that's extra command line arguments are causing this timeout. Looking at https://github.com/Ullaakut/nmap/blob/master/nmap.go#L87 I see that every Run() invocations adds to args slice that causes timeout error after some time.

**Comment by Ullaakut** [comment]
Hi @sm97, indeed you are right, as it is the scanner can't be reused multiple times. This needs to be fixed

**Comment by sm97** [comment]
@Ullaakut please review my PR

**Comment by sm97** [comment]
I found a bug in my code. I used nmap.NewScanner() with nmap.WithContext(ctx) option outside of my scanning loop.
So nmap started to timeout right after context timeout have exceed.
Moving  context creation and nmap.NewScanner() into loop has fixed an issue.
So my PR is rather cosmetic - it just removes nmap options duplication :)
