### ISSUE TITLE
Service Version details not showing up

### ISSUE THREAD

**Issue by katey909** [Ullaakut/nmap#83]
nmap.WithServiceInfo(), not returning service version details.

**Comment by katey909** [comment]
### nmap.WithServiceInfo(),### nmap.WithScripts("vulners.nse") 
output missing

**Comment by Ullaakut** [comment]
Hi @katey909, could you please show an example of your code and how you attempt to read the service info from the returned results?

**Comment by katey909** [comment]
package main

import (
	"context"
	"fmt"
	"log"
	"time"

	"github.com/Ullaakut/nmap/v2"
)

func main() {
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Minute)
	defer cancel()

	// with a 5 minute timeout.
	//nmap -sV -v -F -Pn --script vulners.nse
	//nmap -sU -v -F -Pn
	scanner, err := nmap.NewScanner(
		nmap.WithTargets("8.8.8.8"),
		//nmap.WithTargetInput("target_list.txt"),
		//nmap.WithPrivileged(),
		//-sV
		nmap.WithServiceInfo(),
		//-v
		//nmap.WithVerbosity(2),
		//-F
		nmap.WithFastMode(),
		//-Pn
		nmap.WithSkipHostDiscovery(),
		//-script
		nmap.WithScripts("vulners.nse"),
		//-sU
		//nmap.WithUDPScan(),

		//nmap.WithMaxParallelism(10),

		//nmap.WithPorts("1-1000"),
		//nmap.WithOSDetection(),

		nmap.WithContext(ctx),
	)
	if err != nil {
		log.Fatalf("unable to create nmap scanner: %v", err)
	}

	result, warnings, err := scanner.Run()
	if err != nil {
		log.Fatalf("unable to run nmap scan: %v", err)
	}

	if warnings != nil {
		log.Printf("Warnings: \n %v", warnings)
	}

	// Use the results to print an example output
	for _, host := range result.Hosts {
		if len(host.Ports) == 0 || len(host.Addresses) == 0 {
			continue
		}

		fmt.Printf("Host %q:\n", host.Addresses[0])

		for _, port := range host.Ports {
			fmt.Printf("\tPort %d/%s %s %s %s \n", port.ID, port.Protocol, port.State, port.Service.Name, port.Service.Version)
			//fmt.Printf("%+v\n",port)
		}
	}

	fmt.Printf("Nmap done: %d hosts up scanned in %3f seconds\n", len(result.Hosts), result.Stats.Finished.Elapsed)
}

**Comment by Ullaakut** [comment]
And what is the output that you get when running this? The only port you should see with version info is the `443` port and since you're scanning `8.8.8.8` which is one of Google's public DNSes, it's just an HTTP server that doesn't expose its version information.

I'd recommend trying this out on another IP than a Google DNS, since obviously they're exposing as little information as possible on their public hosts.

**Comment by katey909** [comment]
I had issue with output command. port.Service.Version does not display all the info. And worked for other IP's too. 
Thank You.
