### ISSUE TITLE
Misunderstanding between Configuration and Confidence

### ISSUE THREAD

**Issue by mxrch** [Ullaakut/nmap#84]
I think you interpreted the "conf" nmap parameter as "Configuration" while it means "Confidence".
The attribute : https://pkg.go.dev/github.com/Ullaakut/nmap/v2#Service.Configuration
Nmap documentation : https://nmap.org/book/output-formats-xml-output.html#output-formats-xml-port-elements

I'll provide a PR !

**Comment by mxrch** [comment]
Here is the PR ! https://github.com/Ullaakut/nmap/pull/85

**Comment by Ullaakut** [comment]
Hi @mxrch ! Thank you very much :) That indeed seems to be the case. Great catch!
