### ISSUE TITLE
Function that return options as string

### ISSUE THREAD

**Issue by cyrinux** [Ullaakut/nmap#86]
Hi,
Thanks for this lib!
Could you please add a func that return all the nmap options/params passed to the scanner?
Regards,

**Comment by Ullaakut** [comment]
Hi @cyrinux! I don't have much time to work on this project at the moment, but this should be really simple to do, so if you're up for it feel free to contribute :) Otherwise, I've added some labels to encourage external contributors to take a look at the feature you're asking for.
