### ISSUE TITLE
NIC Vendor not being shown

### ISSUE THREAD

**Issue by Noman-Aziz** [Ullaakut/nmap#94]
Hello, i am trying to find out IP, MAC and NIC Vendor of devices, but the scan only shows IP and MAC. Here is my code,

```
func main() {
	scanner, err := nmap.NewScanner(
		nmap.WithTargets("192.168.18.0/24"),
		nmap.WithFastMode(),
	)
	if err != nil {
		log.Fatalf("unable to create nmap scanner: %v", err)
	}

	result, _, err := scanner.Run()
	if err != nil {
		log.Fatalf("nmap scan failed: %v", err)
	}

	for _, h := range result.Hosts {
		fmt.Println(h)
		//fmt.Println(h.Addresses[0])
		//fmt.Println(h.Addresses[1])
	}
}
```

How can i also show the Vendor?

**Comment by Ullaakut** [comment]
Hi @Noman-Aziz .

To see vendor information (when available), you need to use the `-sV` flag, which is done by passing the option `nmap.WithServiceInfo()` during construction.

**Comment by Noman-Aziz** [comment]
Thank you, it works now.
