### ISSUE TITLE
Using `regexp.Match` or related in a loop, should use `regexp.Compile`

### ISSUE THREAD

**Issue by ChnMig** [Ullaakut/nmap#95]
Hi developers, I'm using vscode for development, and after I clone the source code, I found a prompt telling me that I can optimize at https://github.com/Ullaakut/nmap/blob/master/iflist.go#L71, 
which is made possible by the vscode built-in plugin https://github.com/dominikh/go-tools, 
whose optimization ID is SA6000, https://staticcheck.io/docs/checks/#SA6000
I have modified the code locally, the original code is
``` Go
	for i, line := range lines {
		if match, _ := regexp.MatchString(`[\*]INTERFACES[\*]`, line); match {
			for _, l := range lines[i+2:] {
				if iface := convertInterface(l); iface != nil {
					list.Interfaces = append(list.Interfaces, iface)
				}
			}
		}

		if match, _ := regexp.MatchString(`[\*]ROUTES[\*]`, line); match {
			for _, l := range lines[i+2:] {
				if route := convertRoute(l); route != nil {
					list.Routes = append(list.Routes, route)
				}
			}
		}
	}
```
The modified code is similar to
``` Go

	interfaceRegex, _ := regexp.Compile(`[\*]INTERFACES[\*]`) // Pre-compiled regular expressions
	routerRegex, _ := regexp.Compile(`[\*]ROUTES[\*]`)        // Pre-compiled regular expressions
	for i, line := range lines {
		if match := interfaceRegex.MatchString(line); match {
			for _, l := range lines[i+2:] {
				if iface := convertInterface(l); iface != nil {
					list.Interfaces = append(list.Interfaces, iface)
				}
			}
		}

		if match := routerRegex.MatchString(line); match {
			for _, l := range lines[i+2:] {
				if route := convertRoute(l); route != nil {
					list.Routes = append(list.Routes, route)
				}
			}
		}
	}
```
Or it's a good idea to run `regexp.Compile` directly before everything starts, for example in some initialization function, to avoid recompiling the functions `parseInterfaces` every time they are called

**Comment by elivlo** [comment]
Hi @ChnMig,
indeed you have found a good optimization for the code that should be replaced.

I ran the tool `staticcheck` and found out that there are five more lines of code to optimize:
```
iflist.go:71:18: calling regexp.MatchString in a loop has poor performance, consider using regexp.Compile (SA6000)
iflist.go:79:18: calling regexp.MatchString in a loop has poor performance, consider using regexp.Compile (SA6000)
nmap.go:332:3: should replace loop with warnings = append(warnings, strings.Split(strings.Trim(stderrBuf.String(), "\n"), "\n")...) (S1011)
xml_test.go:227:10: unnecessary use of fmt.Sprintf (S1039)
xml_test.go:230:10: unnecessary use of fmt.Sprintf (S1039)
xml_test.go:234:10: unnecessary use of fmt.Sprintf (S1039)
xml_test.go:240:10: unnecessary use of fmt.Sprintf (S1039)
```

To answer your question, I'm not quite sure, if it is needed to call a initialization function to do  a `precompilation` of the regex. That's because the `iflist` command in nmap is used to find local interfaces and routes that should not change in such short intervals.
We could also add this test to the Github actions.

**Comment by ChnMig** [comment]
@elivlo Thanks for your reply, the tool you wrote is very interesting, I'm trying to write a new project that calls masscan the way you did, that's what I need. 
I agree with you, so I will close issues, because you already know the problem
