### ISSUE TITLE
bug: WithTargets, if targets is 10000 to shell cmd args, too long

### ISSUE THREAD

**Issue by hktalent** [Ullaakut/nmap#98]
```
func WithTargets(targets ...string) func(*Scanner) {
	return func(s *Scanner) {
		s.args = append(s.args, targets...)
	}
}
```

**Comment by Ullaakut** [comment]
Hi @hktalent !

Thanks for reporting that issue. In that case, use `WithTargetInput` instead. Having 10000 targets specified using the `nmap` command in a shell would result in the exact same behavior.
